# Generated by Django 5.2.14 on 2026-05-10 18:44

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="address_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institution",
            name="address_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institution",
            name="address_postal_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="institution",
            name="address_street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="institution",
            name="primary_contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="institution",
            name="secondary_contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="institution",
            name="type",
            field=models.CharField(
                choices=[("school", "School"), ("university", "University")],
                default="school",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="registration_number",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[A-Z0-9]{6,12}$")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("revoked", "Revoked"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
