# Generated by Django 5.2.5 on 2026-05-12 18:45

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_address_city_institution_address_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionOnboardingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending_sa_review', 'Pending SA review'), ('with_compliance', 'With compliance'), ('compliance_done', 'Compliance review complete'), ('pending_board', 'Pending board decision'), ('board_approved', 'Board approved'), ('board_rejected', 'Board rejected'), ('rejected', 'Rejected'), ('account_created', 'IPC account created'), ('withdrawn', 'Withdrawn by applicant')], db_index=True, default='pending_sa_review', max_length=32)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('university', 'University')], default='school', max_length=20)),
                ('registration_number', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^[A-Z0-9]{6,12}$')])),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_postal_code', models.CharField(blank=True, max_length=30)),
                ('address_country', models.CharField(blank=True, max_length=100)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('secondary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('ipc_first_name', models.CharField(max_length=150)),
                ('ipc_last_name', models.CharField(max_length=150)),
                ('ipc_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
