# Generated by Django 5.2.5 on 2026-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_otp_created_at_user_email_otp_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_otp_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
