# Generated by Django 5.2.14 on 2026-05-10 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("provisional", "Provisional"), ("full", "Full")],
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("conditions", models.JSONField(default=list)),
                ("crypto_signature", models.TextField(blank=True)),
                ("qr_secret", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license",
                        to="institutions.institution",
                    ),
                ),
            ],
        ),
    ]
