# Generated by Django 5.2.14 on 2026-05-10 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="license",
            old_name="qr_secret",
            new_name="qr_code_secret",
        ),
        migrations.AddField(
            model_name="license",
            name="board_resolution_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        "ALTER TABLE licenses_license DROP CONSTRAINT IF EXISTS licenses_license_pkey;",
                        "ALTER TABLE licenses_license DROP COLUMN id;",
                        "ALTER TABLE licenses_license ADD COLUMN id uuid NOT NULL DEFAULT gen_random_uuid();",
                        "ALTER TABLE licenses_license ADD CONSTRAINT licenses_license_pkey PRIMARY KEY (id);",
                        "ALTER TABLE licenses_license ALTER COLUMN id DROP DEFAULT;",
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="license",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("revoked", "Revoked"),
                    ("expired", "Expired"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
