# Generated by Django 5.2.14 on 2026-05-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccreditationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_number", models.CharField(max_length=100, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("form_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("rfai", "Request For Additional Information"),
                            ("site_inspection", "Site Inspection"),
                            ("board_decision", "Board Decision"),
                            ("license_issued", "License Issued"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="institutions.institution",
                    ),
                ),
            ],
        ),
    ]
