# Generated by Django 5.2.14 on 2026-05-10 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accreditationapplication",
            name="status",
        ),
        migrations.AddField(
            model_name="accreditationapplication",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("pending_officer_assignment", "Pending Officer Assignment"),
                    ("under_officer_review", "Under Officer Review"),
                    ("additional_info_requested", "Additional Information Requested"),
                    ("site_inspection_scheduled", "Site Inspection Scheduled"),
                    ("pending_board_decision", "Pending Board Decision"),
                    ("board_decision_recorded", "Board Decision Recorded"),
                    ("license_issued", "License Issued"),
                ],
                default="draft",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="accreditationapplication",
            name="current_step",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="accreditationapplication",
            name="last_modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        # BigAutoField -> UUIDField: PostgreSQL cannot cast bigint to uuid. Replace the
        # column instead of ALTER TYPE ... USING (which Django would emit).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        "ALTER TABLE applications_accreditationapplication "
                        "DROP CONSTRAINT IF EXISTS applications_accreditationapplication_pkey;",
                        "ALTER TABLE applications_accreditationapplication DROP COLUMN id;",
                        "ALTER TABLE applications_accreditationapplication "
                        "ADD COLUMN id uuid NOT NULL DEFAULT gen_random_uuid();",
                        "ALTER TABLE applications_accreditationapplication "
                        "ADD CONSTRAINT applications_accreditationapplication_pkey "
                        "PRIMARY KEY (id);",
                        "ALTER TABLE applications_accreditationapplication "
                        "ALTER COLUMN id DROP DEFAULT;",
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="accreditationapplication",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="accreditationapplication",
            name="type",
            field=models.CharField(
                choices=[
                    ("school", "School"),
                    ("programme", "Programme"),
                    ("university_provisional", "University Provisional"),
                    ("university_full", "University Full"),
                ],
                max_length=30,
            ),
        ),
    ]
