# Generated by Django 5.2.14 on 2026-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_id",
            field=models.UUIDField(),
        ),
    ]
